/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include<stdint.h>
#include<stdio.h>
void UsageFault_Handler_c(uint32_t *pMSP);
int main(void)
{
	//kullancı hatası,hafıza yönetim hatası,veri yolu hatası
	uint32_t *pSHCSR=(uint32_t*)0xE000ED24;
	*pSHCSR |=(1<<16);//mem mange
	*pSHCSR |=(1<<17);//bus fault
	*pSHCSR |=(1<<18);//usage fault
	//bazı geçersiz verileri yürütelim
	uint32_t *pSRAM=(uint32_t*)0x20010000;
	*pSRAM=0xFFFFFFFF;

	void (*some_address) (void);
	some_address=(void*)0x20010001;
	some_address();

	for(;;);
}
  void  HardFault_Handler()
  {
	  printf("exception:HardFault\n");
	  while(1);
  }
  void	MemManage_Handler()
  {
	  printf("exception:MemManage\n");
	  while(1);
  }
  void	BusFault_Handler()
  {
	  printf("exception:BusFault\n");
	  while(1);
  }
  __attribute__ ((naked)) void UsageFault_Handler(void) //çıplak işlev diyoruz buna buradan diger _c adlı fonksiyona atlıyor r0 degeri kopyalanıyor
  {
		// burada MSP'nin değerini çıkardık.
		// kural dışı durum girişi sırasında kaydedilen yığın çerçevesinin (iş parçacığı modu) temel adresi
		// iş parçacığı modundan işleyici moduna
	  __asm("MRS r0,MSP");
	  __asm(" B UsageFault_Handler_c ");

  }
  void	UsageFault_Handler_c(uint32_t *pBaseStackFrame)
  {
	  uint32_t *pUFSR=(uint32_t*)0xE000ED2A;
	  printf("exception:UsageFault\n");
	  printf("UFSR:%lx\n",(*pUFSR)&0xFFFF);
	  printf ( "pBaseStackFrame=%p\n" , pBaseStackFrame);
	  printf("value of R0 =%lx\n",pBaseStackFrame[0]);
	  printf("value of R1 =%lx\n",pBaseStackFrame[1]);
	  printf("value of R2 =%lx\n",pBaseStackFrame[2]);
	  printf("value of R3 =%lx\n",pBaseStackFrame[3]);
	  printf("value of R12 =%lx\n",pBaseStackFrame[4]);
	  printf("value of LR =%lx\n",pBaseStackFrame[5]);
	  printf("value of PC =%lx\n",pBaseStackFrame[6]);
	  printf("value of XPSR =%lx\n",pBaseStackFrame[7]);
	  while(1);
  }
